sudo: false

language: go

go:
  - 1.9.x
  - 1.x

git:
  depth: 1

notifications:
  email: false

install:
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...
  - export PATH=$PATH:$HOME/gopath/src/github.com/blueskan/godiator

script:
  - ginkgo -v -r
  - go build